set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[0]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[1]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[2]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[3]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[4]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[5]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[6]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[7]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[8]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[9]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[10]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[11]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[12]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[13]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[14]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[15]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[16]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_addr[17]

set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[0]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[1]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[2]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[3]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[4]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[5]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[6]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[7]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[8]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[9]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[10]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[11]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[12]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[13]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[14]
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_io[15]

set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_CE
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_OE
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_WE
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_LB
set_instance_assignment -name IO_STANDARD "3.3 V" -to sram_UB

set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[8]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[9]

set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[7]

set_location_assignment PIN_B25 -to sram_addr[0]
set_location_assignment PIN_B26 -to sram_addr[1]
set_location_assignment PIN_H19 -to sram_addr[2]
set_location_assignment PIN_H20 -to sram_addr[3]
set_location_assignment PIN_D25 -to sram_addr[4]
set_location_assignment PIN_C25 -to sram_addr[5]
set_location_assignment PIN_J20 -to sram_addr[6]
set_location_assignment PIN_J21 -to sram_addr[7]
set_location_assignment PIN_D22 -to sram_addr[8]
set_location_assignment PIN_E23 -to sram_addr[9]
set_location_assignment PIN_G20 -to sram_addr[10]
set_location_assignment PIN_F21 -to sram_addr[11]
set_location_assignment PIN_E21 -to sram_addr[12]
set_location_assignment PIN_F22 -to sram_addr[13]
set_location_assignment PIN_J25 -to sram_addr[14]
set_location_assignment PIN_J26 -to sram_addr[15]
set_location_assignment PIN_N24 -to sram_addr[16]
set_location_assignment PIN_M24 -to sram_addr[17]

set_location_assignment PIN_E24 -to sram_io[0]
set_location_assignment PIN_E25 -to sram_io[1]
set_location_assignment PIN_K24 -to sram_io[2]
set_location_assignment PIN_K23 -to sram_io[3]
set_location_assignment PIN_F24 -to sram_io[4]
set_location_assignment PIN_G24 -to sram_io[5]
set_location_assignment PIN_L23 -to sram_io[6]
set_location_assignment PIN_L24 -to sram_io[7]
set_location_assignment PIN_H23 -to sram_io[8]
set_location_assignment PIN_H24 -to sram_io[9]
set_location_assignment PIN_H22 -to sram_io[10]
set_location_assignment PIN_J23 -to sram_io[11]
set_location_assignment PIN_F23 -to sram_io[12]
set_location_assignment PIN_G22 -to sram_io[13]
set_location_assignment PIN_L22 -to sram_io[14]
set_location_assignment PIN_K21 -to sram_io[15]

set_location_assignment PIN_N23 -to sram_CE
set_location_assignment PIN_M22 -to sram_OE
set_location_assignment PIN_G25 -to sram_WE
set_location_assignment PIN_H25 -to sram_LB
set_location_assignment PIN_M25 -to sram_UB

set_location_assignment PIN_F7 -to LEDR[0]
set_location_assignment PIN_F6 -to LEDR[1]
set_location_assignment PIN_G6 -to LEDR[2]
set_location_assignment PIN_G7 -to LEDR[3]
set_location_assignment PIN_J8 -to LEDR[4]
set_location_assignment PIN_J7 -to LEDR[5]
set_location_assignment PIN_K10 -to LEDR[6]
set_location_assignment PIN_K8 -to LEDR[7]
set_location_assignment PIN_H7 -to LEDR[8]
set_location_assignment PIN_J10 -to LEDR[9]

set_location_assignment PIN_L7 -to LEDG[0]
set_location_assignment PIN_K6 -to LEDG[1]
set_location_assignment PIN_D8 -to LEDG[2]
set_location_assignment PIN_E9 -to LEDG[3]
set_location_assignment PIN_A5 -to LEDG[4]
set_location_assignment PIN_B6 -to LEDG[5]
set_location_assignment PIN_H8 -to LEDG[6]
set_location_assignment PIN_H9 -to LEDG[7]